### PR TITLE
Issue UPHRH #8469 feat - Enter qr code button hide from classic theme

### PR DESCRIPTION
**Pull request by sohailamjad12**
# SunbirdEd - Portal
---

## Enter Qr code button  hide from classic theme as already we don't have in joyfull theme and same enter qr code functionality we have in search functionality
---

#### Example
- [x] Applicable
- [ ] Not applicable

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Enhancement (additive changes to improve performance)
- [ ] This change requires a documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by rajeshkumaravel — CHANGES_REQUESTED** [review]
@sohailamjad12 
- Feature cannot be directly removed
- Please make this configurable

CC: @mangeshmane @rajeevsathish

**Comment by devendra-tarento** [comment]
@rajeshkumaravel Enter Qr code button is already removed from Joyful theme and i think reason for this could be - search input field is accepting QR code in it (hence having a Enter QR code button and on click launching a popup with input field to enter qr code become obsolete). Due to the same reason we deleted QR code button from UI in classic theme rather than making it configurable.  Please let us know your input on this if still it needs to be made configurable.

**Comment by rajeshkumaravel** [comment]
> @rajeshkumaravel Enter Qr code button is already removed from Joyful theme and i think reason for this could be - search input field is accepting QR code in it (hence having a Enter QR code button and on click launching a popup with input field to enter qr code become obsolete). Due to the same reason we deleted QR code button from UI in classic theme rather than making it configurable. Please let us know your input on this if still it needs to be made configurable.

@vinukumar-vs @Krishnaj20 @rajeevsathish Can we go ahead ?

**Comment by Krishnaj20** [comment]
@rajeshkumaravel - I'm unable to comprehend what is getting removed? The search box in both the themes has 'Search or enter QR code'.

**Comment by vinukumar-vs** [comment]
@devendra-tarento What is reason of taking it off in classic theme. If you have any specific requirement, initiate the discussion thread to know the details. So that community people know the reason of taking it out & helps to track for future.

@Krishnaj20 @rajeevsathish

**Comment by devendra-tarento** [comment]
@vinukumar-vs The reason of taking it off in classic theme:

We don't need to search content through QR code feature and while working on **to hide it through form configuration** we observed that **Enter Qr Code** button is not there in Joyful theme as **Search or enter qr code** input field provides the same capability. So same thing can be adopted in classic theme as well.

I have initiated a discussion thread [here](https://github.com/Sunbird-Ed/Community/discussions/362)
Please go through it.

**Comment by devendra-tarento** [comment]
@rajeshkumaravel @vinukumar-vs Please check the comments from @Krishnaj20 on discussion forum [here](https://github.com/Sunbird-Ed/Community/discussions/362) and take further action on it.

**Comment by rajeshkumaravel** [comment]
@devendra-tarento 
Please check latest comment by @vinukumar-vs 
CC: @Krishnaj20 @rajeevsathish  @mahesh-maney

**Pull request closed without merging**
